### ISSUE TITLE
Reproducible Seg Fault / Core Dump 

### ISSUE THREAD

**Issue by mckittri** [boonproject/boon#287]
#
# A fatal error has been detected by the Java Runtime Environment:
This is using Boon 0.24.   I believe the rest of the pertinent details are below:

#
#  SIGSEGV (0xb) at pc=0x0000003547d378ba, pid=5136, tid=140667149842176
#
# JRE version: OpenJDK Runtime Environment (7.0_51-b02) (build 1.7.0_51-mockbuild_2014_01_15_01_39-b00)
# Java VM: OpenJDK 64-Bit Server VM (24.45-b08 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x1378ba]  __tls_get_addr@@GLIBC_2.3+0x1378ba
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Current thread (0x00007fef280a0000):  JavaThread "Thread-12-b-0" [_thread_in_native, id=5228, stack(0x00007fef9f6f7000,0x00007fef9f7f8000)]

siginfo:si_signo=SIGSEGV: si_errno=0, si_code=1 (SEGV_MAPERR), si_addr=0x0000000000000000

<trunc>

Stack: [0x00007fef9f6f7000,0x00007fef9f7f8000],  sp=0x00007fef9f7f4a08,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x1378ba]  __tls_get_addr@@GLIBC_2.3+0x1378ba
V  [libjvm.so+0x6977a6]  JVM_RaiseSignal+0x60ab6
V  [libjvm.so+0x3f27d6]  dlerror+0x3f27d6
V  [libjvm.so+0x8adc16]  JVM_handle_linux_signal+0xf22c6
V  [libjvm.so+0x900d33]  JVM_handle_linux_signal+0x1453e3
j  sun.misc.Unsafe.defineAnonymousClass(Ljava/lang/Class;[B[Ljava/lang/Object;)Ljava/lang/Class;+0
j  java.lang.invoke.InvokerBytecodeGenerator.loadAndInitializeInvokerClass([B[Ljava/lang/Object;)Ljava/lang/Class;+8
j  java.lang.invoke.InvokerBytecodeGenerator.loadMethod([B)Ljava/lang/invoke/MemberName;+6
j  java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCode(Ljava/lang/invoke/LambdaForm;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/MemberName;+17
j  java.lang.invoke.LambdaForm.compileToBytecode()Ljava/lang/invoke/MemberName;+65
j  java.lang.invoke.DirectMethodHandle.makePreparedLambdaForm(Ljava/lang/invoke/MethodType;I)Ljava/lang/invoke/LambdaForm;+617
j  java.lang.invoke.DirectMethodHandle.preparedLambdaForm(Ljava/lang/invoke/MethodType;I)Ljava/lang/invoke/LambdaForm;+17
j  java.lang.invoke.DirectMethodHandle.preparedLambdaForm(Ljava/lang/invoke/MemberName;)Ljava/lang/invoke/LambdaForm;+163
j  java.lang.invoke.DirectMethodHandle.make(Ljava/lang/Class;Ljava/lang/invoke/MemberName;)Ljava/lang/invoke/DirectMethodHandle;+64
j  java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(BLjava/lang/Class;Ljava/lang/invoke/MemberName;ZLjava/lang/Class;)Ljava/lang/invoke/MethodHandle;+153
j  java.lang.invoke.MethodHandles$Lookup.getDirectMethod(BLjava/lang/Class;Ljava/lang/invoke/MemberName;Ljava/lang/Class;)Ljava/lang/invoke/MethodHandle;+32
j  java.lang.invoke.MethodHandles$Lookup.unreflect(Ljava/lang/reflect/Method;)Ljava/lang/invoke/MethodHandle;+72
j  org.boon.core.reflection.impl.MethodAccessImpl.methodHandle()Ljava/lang/invoke/MethodHandle;+8
j  org.boon.core.reflection.impl.MethodAccessImpl.<init>(Ljava/lang/reflect/Method;)V+33
j  org.boon.core.reflection.ClassMeta.<init>(Ljava/lang/Class;)V+505
j  org.boon.core.reflection.ClassMeta.classMeta(Ljava/lang/Class;)Lorg/boon/core/reflection/ClassMeta;+25
j  org.boon.core.reflection.Reflection.newInstance(Ljava/lang/Class;)Ljava/lang/Object;+3
j  org.boon.core.reflection.Mapper.fromValueMap(Ljava/util/Map;Ljava/lang/Class;)Ljava/lang/Object;+1
j  org.boon.core.reflection.Mapper.fromValueMapHandleValueCase(Ljava/lang/Object;Lorg/boon/core/reflection/fields/FieldAccess;Lorg/boon/core/Value;)V+256
j  org.boon.core.reflection.Mapper.fromValueMap(Ljava/util/Map;Ljava/lang/Class;)Ljava/lang/Object;+274
j  org.boon.json.JsonMappingParser.finalExtract(Ljava/lang/Class;Ljava/lang/Object;)Ljava/lang/Object;+18
j  org.boon.json.JsonMappingParser.parse(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Object;+38
j  org.boon.json.implementation.ObjectMapperImpl.readValue(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;+9

<trunc>

**Comment by RichardHightower** [comment]
Please upgrade to latest boon and see if the problem persists. Also send a small code snippet to reproduce issue.

**Comment by mckittri** [comment]
I upgraded to .30 and still have the issue.     I put an updated snippet of the stacktrace in case the line numbers changed.

The code is part of an Apache Storm Trident function....  I edited out some of the Trident overhead for clarity   

import org.boon.json.JsonFactory;
import org.boon.json.ObjectMapper;
....
	private ObjectMapper mapper;
	private Class<T> clazz;	

	public SomeUnmarshallCode(Class<T> clazz) {
		this.clazz = clazz;
	}
....
		mapper = JsonFactory.create();
... 
               T object = mapper.readValue(tuple.getString(0), this.clazz);


Stack: [0x00007fba3c553000,0x00007fba3c654000],  sp=0x00007fba3c650af8,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x1378ba]  __tls_get_addr@@GLIBC_2.3+0x1378ba
V  [libjvm.so+0x6977a6]  JVM_RaiseSignal+0x60ab6
V  [libjvm.so+0x3f27d6]  dlerror+0x3f27d6
V  [libjvm.so+0x8adc16]  JVM_handle_linux_signal+0xf22c6
V  [libjvm.so+0x900d33]  JVM_handle_linux_signal+0x1453e3
j  sun.misc.Unsafe.defineAnonymousClass(Ljava/lang/Class;[B[Ljava/lang/Object;)Ljava/lang/Class;+0
j  java.lang.invoke.InvokerBytecodeGenerator.loadAndInitializeInvokerClass([B[Ljava/lang/Object;)Ljava/lang/Class;+8
j  java.lang.invoke.InvokerBytecodeGenerator.loadMethod([B)Ljava/lang/invoke/MemberName;+6
j  java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCode(Ljava/lang/invoke/LambdaForm;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/MemberName;+17
j  java.lang.invoke.LambdaForm.compileToBytecode()Ljava/lang/invoke/MemberName;+65
j  java.lang.invoke.DirectMethodHandle.makePreparedLambdaForm(Ljava/lang/invoke/MethodType;I)Ljava/lang/invoke/LambdaForm;+617
j  java.lang.invoke.DirectMethodHandle.preparedLambdaForm(Ljava/lang/invoke/MethodType;I)Ljava/lang/invoke/LambdaForm;+17
j  java.lang.invoke.DirectMethodHandle.preparedLambdaForm(Ljava/lang/invoke/MemberName;)Ljava/lang/invoke/LambdaForm;+163
j  java.lang.invoke.DirectMethodHandle.make(Ljava/lang/Class;Ljava/lang/invoke/MemberName;)Ljava/lang/invoke/DirectMethodHandle;+64
j  java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(BLjava/lang/Class;Ljava/lang/invoke/MemberName;ZLjava/lang/Class;)Ljava/lang/invoke/MethodHandle;+153
j  java.lang.invoke.MethodHandles$Lookup.getDirectMethod(BLjava/lang/Class;Ljava/lang/invoke/MemberName;Ljava/lang/Class;)Ljava/lang/invoke/MethodHandle;+32
j  java.lang.invoke.MethodHandles$Lookup.unreflect(Ljava/lang/reflect/Method;)Ljava/lang/invoke/MethodHandle;+72
j  org.boon.core.reflection.impl.MethodAccessImpl.methodHandle()Ljava/lang/invoke/MethodHandle;+8
j  org.boon.core.reflection.impl.MethodAccessImpl.<init>(Ljava/lang/reflect/Method;)V+96
j  org.boon.core.reflection.ClassMeta.<init>(Ljava/lang/Class;)V+505
j  org.boon.core.reflection.ClassMeta.classMeta(Ljava/lang/Class;)Lorg/boon/core/reflection/ClassMeta;+25
j  org.boon.core.reflection.Reflection.newInstance(Ljava/lang/Class;)Ljava/lang/Object;+3
j  org.boon.core.reflection.MapperSimple.fromValueMap(Ljava/util/Map;Ljava/lang/Class;)Ljava/lang/Object;+1
j  org.boon.core.reflection.MapperSimple.fromValueMapHandleValueCase(Ljava/lang/Object;Lorg/boon/core/reflection/fields/FieldAccess;Lorg/boon/core/Value;)V+288
j  org.boon.core.reflection.MapperSimple.fromValueMap(Ljava/util/Map;Ljava/lang/Class;)Ljava/lang/Object;+219
j  org.boon.json.JsonMappingParser.finalExtract(Ljava/lang/Class;Ljava/lang/Object;)Ljava/lang/Object;+18
j  org.boon.json.JsonMappingParser.parse(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Object;+38
j  org.boon.json.implementation.ObjectMapperImpl.readValue(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;+9

**Comment by RichardHightower** [comment]
A segfault is a nasty business. 

```java
package org.boon.bugs;

import org.boon.json.JsonFactory;
import org.boon.json.ObjectMapper;
import org.junit.Test;

import static org.boon.Boon.puts;

/**
 * Created by rhightower on 1/5/15.
 */
public class Bug287 {

    boolean ok;


    public static class SomeClass {
        Class<?> clazz;

        SomeClass(Class<?> clazz) {
            this.clazz = clazz;
        }
    }

    @Test
    public void serializingClassFieldCausesSegFault() {

        SomeClass someClassInstance = new SomeClass(Bug287.class);

        ObjectMapper mapper = JsonFactory.create();

        final String json = mapper.toJson(someClassInstance);

        puts(json);

        SomeClass someClassInstance2 = mapper.readValue("{\"clazz\":\"org.boon.bugs.Bug287\"} ", SomeClass.class);

        ok = someClassInstance2.clazz.getName().equals("org.boon.bugs.Bug287");

    }

}

```

I can't reproduce it. I can see where it is happening and this code is not really used much, and could be initialized lazily so I can likely patch it eventhough I can't reproduce it.

**Comment by RichardHightower** [comment]
I fixed it in the snapshot.

**Comment by mckittri** [comment]
Thanks for the quick response.   I'll pull the snapshot tomorrow.

**Comment by RichardHightower** [comment]
Quick responses are the exception not the norm. I go in spurts.

**Comment by mckittri** [comment]
I just downloaded the zip off github and compiled the snapshot jar.    Unfortunately I am still seeing the segfault.     I grep'd the error report file spit out by the JVM and confirmed I am pointing against the boon snapshot I just compiled.

7f576e87a000-7f576e88a000 r--s 000f6000 fd:00 1074118                    /home/mckittri/.m2/repository/io/fastjson/boon/0.31-SNAPSHOT/boon-0.31-SNAPSHOT.jar

Could the reproduceability be related to the JDK version? 

vm_info: OpenJDK 64-Bit Server VM (24.45-b08) for linux-amd64 JRE (1.7.0_51-mockbuild_2014_01_15_01_39-b00), built on Jan 15 2014 01:48:43 by "mockbuild" with gcc 4.4.7 20120313 (Red Hat 4.4.7-4)

Here's an updated stacktrace:

Stack: [0x00007f5766ff0000,0x00007f57670f1000],  sp=0x00007f57670eb0c8,  free space=1004k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x1378ba]  __tls_get_addr@@GLIBC_2.3+0x1378ba
V  [libjvm.so+0x6977a6]  JVM_RaiseSignal+0x60ab6
V  [libjvm.so+0x3f27d6]  dlerror+0x3f27d6
V  [libjvm.so+0x8adc16]  JVM_handle_linux_signal+0xf22c6
V  [libjvm.so+0x900d33]  JVM_handle_linux_signal+0x1453e3
j  sun.misc.Unsafe.defineAnonymousClass(Ljava/lang/Class;[B[Ljava/lang/Object;)Ljava/lang/Class;+0
j  java.lang.invoke.InvokerBytecodeGenerator.loadAndInitializeInvokerClass([B[Ljava/lang/Object;)Ljava/lang/Class;+8
j  java.lang.invoke.InvokerBytecodeGenerator.loadMethod([B)Ljava/lang/invoke/MemberName;+6
j  java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCode(Ljava/lang/invoke/LambdaForm;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/MemberName;+17
j  java.lang.invoke.LambdaForm.compileToBytecode()Ljava/lang/invoke/MemberName;+65
j  java.lang.invoke.DirectMethodHandle.makePreparedLambdaForm(Ljava/lang/invoke/MethodType;I)Ljava/lang/invoke/LambdaForm;+617
j  java.lang.invoke.DirectMethodHandle.preparedLambdaForm(Ljava/lang/invoke/MethodType;I)Ljava/lang/invoke/LambdaForm;+17
j  java.lang.invoke.DirectMethodHandle.preparedLambdaForm(Ljava/lang/invoke/MemberName;)Ljava/lang/invoke/LambdaForm;+163
j  java.lang.invoke.DirectMethodHandle.make(Ljava/lang/Class;Ljava/lang/invoke/MemberName;)Ljava/lang/invoke/DirectMethodHandle;+64
j  java.lang.invoke.DirectMethodHandle.make(Ljava/lang/invoke/MemberName;)Ljava/lang/invoke/DirectMethodHandle;+17
j  java.lang.invoke.LambdaForm$NamedFunction.initializeInvokers()V+137
j  java.lang.invoke.LambdaForm.<clinit>()V+339
v  ~StubRoutines::call_stub
V  [libjvm.so+0x5d2b4e]  AsyncGetCallTrace+0xe27ee
V  [libjvm.so+0x5d1718]  AsyncGetCallTrace+0xe13b8
V  [libjvm.so+0x595a68]  AsyncGetCallTrace+0xa5708
V  [libjvm.so+0x595d47]  AsyncGetCallTrace+0xa59e7
V  [libjvm.so+0x59648a]  AsyncGetCallTrace+0xa612a
V  [libjvm.so+0x6e81f6]  JVM_RaiseSignal+0xb1506
V  [libjvm.so+0x6eb108]  JVM_RaiseSignal+0xb4418
V  [libjvm.so+0x5cca3a]  AsyncGetCallTrace+0xdc6da
j  java.lang.invoke.DirectMethodHandle.makePreparedLambdaForm(Ljava/lang/invoke/MethodType;I)Ljava/lang/invoke/LambdaForm;+298
j  java.lang.invoke.DirectMethodHandle.preparedLambdaForm(Ljava/lang/invoke/MethodType;I)Ljava/lang/invoke/LambdaForm;+17
j  java.lang.invoke.DirectMethodHandle.preparedLambdaForm(Ljava/lang/invoke/MemberName;)Ljava/lang/invoke/LambdaForm;+163
j  java.lang.invoke.DirectMethodHandle.make(Ljava/lang/Class;Ljava/lang/invoke/MemberName;)Ljava/lang/invoke/DirectMethodHandle;+64
j  java.lang.invoke.DirectMethodHandle.make(Ljava/lang/invoke/MemberName;)Ljava/lang/invoke/DirectMethodHandle;+17
j  java.lang.invoke.LambdaForm$NamedFunction.resolve()V+5
j  java.lang.invoke.DirectMethodHandle.<clinit>()V+482
v  ~StubRoutines::call_stub
V  [libjvm.so+0x5d2b4e]  AsyncGetCallTrace+0xe27ee
V  [libjvm.so+0x5d1718]  AsyncGetCallTrace+0xe13b8
V  [libjvm.so+0x595a68]  AsyncGetCallTrace+0xa5708
V  [libjvm.so+0x595d47]  AsyncGetCallTrace+0xa59e7
V  [libjvm.so+0x59648a]  AsyncGetCallTrace+0xa612a
V  [libjvm.so+0x6e81f6]  JVM_RaiseSignal+0xb1506
V  [libjvm.so+0x6eb108]  JVM_RaiseSignal+0xb4418
V  [libjvm.so+0x5cca3a]  AsyncGetCallTrace+0xdc6da
j  java.lang.invoke.LambdaForm$NamedFunction.resolve()V+5
j  java.lang.invoke.MethodHandleImpl.<clinit>()V+54
v  ~StubRoutines::call_stub
V  [libjvm.so+0x5d2b4e]  AsyncGetCallTrace+0xe27ee
V  [libjvm.so+0x5d1718]  AsyncGetCallTrace+0xe13b8
V  [libjvm.so+0x595a68]  AsyncGetCallTrace+0xa5708
V  [libjvm.so+0x595d47]  AsyncGetCallTrace+0xa59e7
V  [libjvm.so+0x59648a]  AsyncGetCallTrace+0xa612a
V  [libjvm.so+0x6e81f6]  JVM_RaiseSignal+0xb1506
V  [libjvm.so+0x6eb108]  JVM_RaiseSignal+0xb4418
V  [libjvm.so+0x5cca3a]  AsyncGetCallTrace+0xdc6da
j  java.lang.invoke.MethodHandles.<clinit>()V+23
v  ~StubRoutines::call_stub
V  [libjvm.so+0x5d2b4e]  AsyncGetCallTrace+0xe27ee
V  [libjvm.so+0x5d1718]  AsyncGetCallTrace+0xe13b8
V  [libjvm.so+0x595a68]  AsyncGetCallTrace+0xa5708
V  [libjvm.so+0x595d47]  AsyncGetCallTrace+0xa59e7
V  [libjvm.so+0x59648a]  AsyncGetCallTrace+0xa612a
V  [libjvm.so+0x6e81f6]  JVM_RaiseSignal+0xb1506
V  [libjvm.so+0x6eb108]  JVM_RaiseSignal+0xb4418
V  [libjvm.so+0x5cca3a]  AsyncGetCallTrace+0xdc6da
j  org.boon.core.reflection.impl.MethodAccessImpl.<init>()V+16
j  org.boon.core.reflection.ClassMeta$1.<init>()V+1
j  org.boon.core.reflection.ClassMeta.<clinit>()V+4
v  ~StubRoutines::call_stub
V  [libjvm.so+0x5d2b4e]  AsyncGetCallTrace+0xe27ee
V  [libjvm.so+0x5d1718]  AsyncGetCallTrace+0xe13b8
V  [libjvm.so+0x595a68]  AsyncGetCallTrace+0xa5708
V  [libjvm.so+0x595d47]  AsyncGetCallTrace+0xa59e7
V  [libjvm.so+0x59648a]  AsyncGetCallTrace+0xa612a
V  [libjvm.so+0x6e81f6]  JVM_RaiseSignal+0xb1506
V  [libjvm.so+0x6eb108]  JVM_RaiseSignal+0xb4418
V  [libjvm.so+0x5cca3a]  AsyncGetCallTrace+0xdc6da
j  org.boon.core.reflection.Reflection.newInstance(Ljava/lang/Class;)Ljava/lang/Object;+3
j  org.boon.core.reflection.MapperSimple.fromValueMap(Ljava/util/Map;Ljava/lang/Class;)Ljava/lang/Object;+1
j  org.boon.json.JsonMappingParser.finalExtract(Ljava/lang/Class;Ljava/lang/Object;)Ljava/lang/Object;+18
j  org.boon.json.JsonMappingParser.parse(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Object;+38
j  org.boon.json.implementation.ObjectMapperImpl.readValue(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;+9

**Comment by mckittri** [comment]
Followup:   I updated my JDK from the OpenJDK to the latest Oracle version (for Java7).    The error has now stopped happening.     Strange...

./java -version
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

Probably doesn't have anything to do with Boon directly except I can somehow trigger the scenario with Boon.    Just FYI in case anyone else runs into this.   I am still using the snapshot with the patch made by Richard yesterday.   I haven't tried it again with the .30 release jars.
